# Generated by Django 5.0.4 on 2024-04-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_bill_products_billitem_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='employee_generated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
            preserve_default=False,
        ),
    ]
